@id = 7b532ce7-ad78-4fb1-bd90-224a76ebd586
### Fetch all tasks

GET http://localhost:3200/tasks
Content-Type: application/json

### Create new task

POST http://localhost:3200/tasks
Content-Type: application/json

{
  "title": "Hello",
  "date": "2024-04-15T05:59:06.121Z",
  "description": "Lorem ipsum",
  "priority": "normal",
  "status": "todo"
}

### Update task

PUT http://localhost:3200/tasks/{{id}}
Content-Type: application/json

{
  "description": "Test",
  "status": "inProgress"
}

### Delete task

DELETE http://localhost:3200/tasks/{{id}}
Content-Type: application/json
